#ifndef APP_EGUI_CONFIG_H
#define APP_EGUI_CONFIG_H

#define EGUI_CONFIG_SCREEN_WIDTH 428
#define EGUI_CONFIG_SCREEN_HEIGHT 142
#define EGUI_CONFIG_COLOR_DEPTH 16
#define EGUI_CONFIG_PFB_WIDTH 428
#define EGUI_CONFIG_PFB_HEIGHT 16
#define EGUI_CONFIG_PFB_BUFFER_COUNT 1

#define EGUI_CONFIG_DEBUG_LOG_LEVEL 0
#define EGUI_CONFIG_FUNCTION_FONT_STD_FAST_DRAW 0
#define EGUI_CONFIG_FUNCTION_FONT_TRANSFORM_FAST_DRAW 0
#define EGUI_CONFIG_FUNCTION_SUPPORT_MASK 0
#define EGUI_CONFIG_FUNCTION_CANVAS_EXTRA_CLIP 0
#define EGUI_CONFIG_FUNCTION_CANVAS_SPEC_CIRCLE_INFO 0
#define EGUI_CONFIG_CIRCLE_SUPPORT_RADIUS_BASIC_RANGE 16

#endif /* APP_EGUI_CONFIG_H */
